name: Deploy Zendesk App

on:
  push:    
    branches:
      - main

jobs:
  test_deployment:  
    runs-on: ubuntu-latest    
    environment: 
      name: TEST
    strategy:
      matrix:
        node-version: [16.x]
    env:
      ZENDESK_SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
      ZENDESK_EMAIL: ${{ secrets.EMAIL }}
      ZENDESK_API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:      
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}          
      - name: Install zcli
        run: npm i @zendesk/zcli -g
